### ISSUE TITLE
Repository not found

### ISSUE THREAD

**Issue by boris-petrov** [raisercostin/maven-defaults-raisercostin#1]
The [linked repository in the README](https://jcenter.bintray.com/org/raisercostin/maven-defaults-raisercostin/) is a 404. Because of this, version 1.4 of `yanfs` cannot be installed as it depends on `maven-defaults-raisercostin` 1.1.

**Comment by raisercostin** [comment]
Fixed. File available at https://jcenter.bintray.com/org/raisercostin/maven-defaults-raisercostin/1.1/
